version: '3.0'
services:
  mongo:
    image: mongo
    ports:
      - 27000:27017
    environment:
#      - MONGO_INITDB_ROOT_USERNAME="dart_orm_test"
#      - MONGO_INITDB_ROOT_PASSWORD="dart_orm_test"
      - MONGO_INITDB_DATABASE="dart_orm_test"
  postgres:
    image: postgres
    ports:
      - 5000:5432
    environment:
      - POSTGRES_PASSWORD=dart_orm_test
      - POSTGRES_USER=dart_orm_test
      - POSTGRES_DB=dart_orm_test
  mysql:
    image: mysql:5.7
    ports:
      - 3000:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=dart_orm_test
      - MYSQL_USER=dart_orm_test
      - MYSQL_PASSWORD=dart_orm_test
  test:
    image: google/dart:dev
    command: bash -c "pub get && pub run test"
    working_dir: /project
    volumes:
      - .:/project
      - ~/.pub-cache:/root/.pub-cache
    depends_on:
      - mongo
      - postgres
      - mysql
    environment:
      - USE_DOCKER=true